[project]
name = "RandomNumberManager"
version = "0.1"
description = "Manage random number stream state."
readme = {file = "README.md"}
license = {file = "LICENSE"}
authors = [
	{name = "yy-harashima"}
]
dependencies = [
	     "numpy",
]