[project]
name = "rnmanager"
version = "0.2"
description = "Manage random number stream state."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
	{name = "yy-harashima"}
]
dependencies = [
	     "numpy",
]

[tool.setuptools]
package-dir = {"" = "src/site_requests"}